// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANgdhQAigR1GXmwxAWfK58lsgIZm0SWzM',
    appId: '1:981686130457:web:0c88ed31de7d90059f9788',
    messagingSenderId: '981686130457',
    projectId: 'fir-sample-aae4a',
    authDomain: 'fir-sample-aae4a.firebaseapp.com',
    databaseURL: 'https://fir-sample-aae4a.firebaseio.com',
    storageBucket: 'fir-sample-aae4a.appspot.com',
    measurementId: 'G-GHYPW9MJMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBLyMKLnupvkFtOrtYT_GpVkeqZ12CBl8',
    appId: '1:981686130457:android:51a6bf32c868d9c49f9788',
    messagingSenderId: '981686130457',
    projectId: 'fir-sample-aae4a',
    databaseURL: 'https://fir-sample-aae4a.firebaseio.com',
    storageBucket: 'fir-sample-aae4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6nq1XL0rW1eBVc2eG_mxwEKup97jZPg',
    appId: '1:981686130457:ios:d8a7e6a18b1e4adc9f9788',
    messagingSenderId: '981686130457',
    projectId: 'fir-sample-aae4a',
    databaseURL: 'https://fir-sample-aae4a.firebaseio.com',
    storageBucket: 'fir-sample-aae4a.appspot.com',
    androidClientId: '981686130457-5bhsq1c131fvb5h31i44k7ffkrgeaubb.apps.googleusercontent.com',
    iosClientId: '981686130457-fhiljeoof17675cjv48uih2ut4q77dco.apps.googleusercontent.com',
    iosBundleId: 'com.example.ahticketing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz6nq1XL0rW1eBVc2eG_mxwEKup97jZPg',
    appId: '1:981686130457:ios:d8a7e6a18b1e4adc9f9788',
    messagingSenderId: '981686130457',
    projectId: 'fir-sample-aae4a',
    databaseURL: 'https://fir-sample-aae4a.firebaseio.com',
    storageBucket: 'fir-sample-aae4a.appspot.com',
    androidClientId: '981686130457-5bhsq1c131fvb5h31i44k7ffkrgeaubb.apps.googleusercontent.com',
    iosClientId: '981686130457-fhiljeoof17675cjv48uih2ut4q77dco.apps.googleusercontent.com',
    iosBundleId: 'com.example.ahticketing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyaHEX0no8l9tizUQdAG6sPbg3sPgJIA0',
    appId: '1:981686130457:web:abd389efe9a73d3a9f9788',
    messagingSenderId: '981686130457',
    projectId: 'fir-sample-aae4a',
    authDomain: 'fir-sample-aae4a.firebaseapp.com',
    databaseURL: 'https://fir-sample-aae4a.firebaseio.com',
    storageBucket: 'fir-sample-aae4a.appspot.com',
    measurementId: 'G-L45LKJ3S5Z',
  );

}