// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUFsrrvx7_gBubGHAjJUceUR_X4soP4XE',
    appId: '1:522544587505:web:65ed9e3c32d7095ed2bf50',
    messagingSenderId: '522544587505',
    projectId: 'test-environment-841c3',
    authDomain: 'test-environment-841c3.firebaseapp.com',
    databaseURL: 'https://test-environment-841c3.firebaseio.com',
    storageBucket: 'test-environment-841c3.appspot.com',
    measurementId: 'G-Q17FPJ4KBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc1nLgJepPp9tQWAHxsBwF-LZGu9loMVU',
    appId: '1:522544587505:android:c80990cfbe5e53a5d2bf50',
    messagingSenderId: '522544587505',
    projectId: 'test-environment-841c3',
    databaseURL: 'https://test-environment-841c3.firebaseio.com',
    storageBucket: 'test-environment-841c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoGR8xi9uzDoOSYLEJ-kH4dSJm9bvfhEA',
    appId: '1:522544587505:ios:648ffeb894aa0306d2bf50',
    messagingSenderId: '522544587505',
    projectId: 'test-environment-841c3',
    databaseURL: 'https://test-environment-841c3.firebaseio.com',
    storageBucket: 'test-environment-841c3.appspot.com',
    iosBundleId: 'com.example.ahticketing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoGR8xi9uzDoOSYLEJ-kH4dSJm9bvfhEA',
    appId: '1:522544587505:ios:648ffeb894aa0306d2bf50',
    messagingSenderId: '522544587505',
    projectId: 'test-environment-841c3',
    databaseURL: 'https://test-environment-841c3.firebaseio.com',
    storageBucket: 'test-environment-841c3.appspot.com',
    iosBundleId: 'com.example.ahticketing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUFsrrvx7_gBubGHAjJUceUR_X4soP4XE',
    appId: '1:522544587505:web:f36f6d250cf566f6d2bf50',
    messagingSenderId: '522544587505',
    projectId: 'test-environment-841c3',
    authDomain: 'test-environment-841c3.firebaseapp.com',
    databaseURL: 'https://test-environment-841c3.firebaseio.com',
    storageBucket: 'test-environment-841c3.appspot.com',
    measurementId: 'G-YVG9JCXD5Y',
  );

}